include objects.mak

CC = gcc
CFLAGS += -Wall -g

LIBS += -llua -lfreeglut -lGLU32 -lOpenGL32 -lwinmm -lgdi32 -lALut -lOpenAL32
CFLAGS += -DFREEGLUT_STATIC
TARGET = opl2.exe

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LIBS)

clean:
	rm -f $(TARGET) $(OBJS)

rebuild: clean $(TARGET)

GEOM = -geometry 640x480+0+0
test: $(TARGET)
	$(TARGET) $(GEOM)
debug: $(TARGET)
	gdb -ex run --args $(TARGET) $(GEOM)
