include objects.mak

CC = gcc
CFLAGS += -Wall -g

LIBS += -llua -lfreeglut -lGLU32 -lOpenGL32 -lwinmm -lgdi32 -lALut -lOpenAL32 -lvorbis -lvorbisfile
CFLAGS += -DFREEGLUT_STATIC
TARGET = opl2.exe

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LIBS)

clean:
	rm -f $(TARGET) $(OBJS)

rebuild: clean $(TARGET)

ARGS = -window 640x480
test: $(TARGET)
	$(TARGET) $(ARGS)
debug: $(TARGET)
	gdb -ex run --args $(TARGET) $(ARGS)
