PSPSDK = $(shell psp-config --pspsdk-path)
PSPDEV = $(shell psp-config --pspdev-path)

include objects.mak

LIBS += -llua -lglut -lGLU -lGL -lALut -lOpenAL32
LIBS += -lpspvfpu -lpsprtc -lpspaudio -lpsphprm -lm

TARGET = opl2
BUILD_PRX = 1
CFLAGS += -Wall -g -G0

include $(PSPSDK)/lib/build.mak

debug: $(TARGET).prx $(TARGET).elf
	psp-gdb -ex "target remote :10001" --args "$(TARGET).elf"
